config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'jobs#index'

  resources :companies, only: [:new, :create, :show, :index] do
    resources :jobs, only: [:new, :create, :show, :index]
  end


  resources :jobs, only: [:show, :index] do
    member do
      get :preview
      get :send_mail
      get :purchase
    end

  end

  get '/categories', to: 'jobs#categories'
  get 'new', to: 'companies#new'
  get '/imprint', to: 'pages#imprint'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
  has_many :jobs, inverse_of: :company
  has_one_attached :photo
  validates :email, presence: true
  validates :name, presence: true
  accepts_nested_attributes_for :jobs, reject_if: :all_blank
  validates_associated :jobs
  after_create :send_emails
  has_rich_text :description, :statement


  # def jobs_attributes=(jobs_attributes)
  #   jobs_attributes.each do |i, job_attributes|
  #     self.jobs.build(job_attributes)
  #   end
  # end

  def new?(email)
    @company = Company.new
    [] << Company.all.find_index { |c| c.email == email }
    [].size <= 1
  end

  def send_emails
    NewPostingMailer.with(company: self).notify_user.deliver_now
    NewPostingMailer.with(company: self).pending_posting.deliver_now
  end
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :company, optional: true
  accepts_nested_attributes_for :company
  validates :title, presence: true
  validates :category, presence: true, inclusion: { in: ['Design',
  'Programming', 'Product (Owner)', 'Sales and Marketing', 'Scrum Master / Agile Coach', 'All Other'] }
  has_rich_text :description

  default_scope { order(created_at: :desc) }

  def new?
    Job.where('created_at >= ?', 2.weeks.ago)
  end

  def featured?
    true if status == 'payed/feature'
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  def index
    @companies = Company.all
  end

  def show
    @company = Company.find(params[:id])
  end

  def new
    @company = Company.new
    @company.jobs.build
  end

  def create
    @company = Company.new(company_params)
    if @company.save
        # NewPostingMailer.notify_user(@company).deliver_now
        # NewPostingMailer.pending_posting(@company).deliver_now
        redirect_to job_path(@company.jobs.first[:id]), notice: "Thank you for posting. You'll receive the conformation via email."
      else
        render 'companies/new', notice: "Ups, there were an error. Please, try again."
    end
    # else
    #   @company = Company.where((params[:email]) == 'email')
    #   redirect_to new_company_job_path(@company)
    # end
  end

  private

  def company_params
    params.require(:company).permit(:name, :statement, :photo, :description, :email, :url, jobs_attributes: [:title, :category, :applying, :description, :type])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    @jobs = Job.where(status: 'payed/featured')
    @jobs = Job.where(status: 'payed')
  end

  def new
    @job = Job.new
    @job.company = Company.find(params[:company_id])
  end

  def create
    @job = Job.new(job_params)
    @company = Company.find(params[:company_id])
    @job.company = @company
    if @job.save
        redirect_to company_preview_path(@job, @company)
        redirect_to send_mail_job_path
    else
      render 'jobs/new', notice: "Ups, there were an error. Please, try again."
    end
  end

  def show
    @job = Job.find(params[:id])
    @company = @job.company
  end

  def preview
    @job = Job.find(params[:id])
    @company = @job.company
  end

  def purchase
    @job = Job.find(params[:id])
    @company = @job.company
  end

  def send_email
    @job = Job.find(params[:id])
    UserMailer.newMail(@job).deliver
    redirect_to company_preview_path(@job, @company)
  end

  private

  def job_params
    params.require(:job).permit(:title, :category, :applying, :description)
  end



end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/companies/_company-posting.html.erb
<div class="content">
  <div class="company-listing-header">
    <div>
      <div class="logo">
        <% if @company.photo.attached? %>
          <%= cl_image_tag company.photo.key, height: 150, width: 200, crop: :fill %>
        <% end %>
      </div>
      <h1><%= @company.name %></h1>
    </div>
  </div>
  <div>

  </div>
</div>

app/views/companies/_form.html.erb
<%=  simple_form_for @company do |f|%>
  <div class="form-partial">
   <h3>First, tell us about the position</h3>
    <%= f.simple_fields_for :jobs do |jobs|  %>
      <%= jobs.input :title, as: :string, label: 'Job Title', error: 'The job title is mandatory' %>
      <%= jobs.input :category, collection: ['Design',
  'Programming', 'Product (Owner)', 'Sales and Marketing', 'Scrum Master / Agile Coach', 'All Other']%>
      <%= jobs.input :job_type, as: :radio_buttons, collection: ['contract', 'freelancer'] %>
      <%= jobs.input :applying, as: :string, label: 'How to Apply' %>
      <%= jobs.input :description, as: :text, label: 'Job Description' %>
    <% end %>
  </div>
  <div class="form-partial">
    <h3>Tell Us More About Your Company</h3>
    <!-- <p>Posted before? Just enter your email, all other info will be pulled in from your last position!</p> -->
    <%= f.input :name, label: 'Company Name' %>
    <%= f.input :photo, as: :file, label: "Company's Logo", input_html: { class: 'image-input'} %>
    <%= f.input :statement, label: 'Company Statement (optional)' %>
    <%= f.input :url, label: "Company's Website URL" %>
    <%= f.input :email, label: 'Email' %>
    <%= f.input :description, as: :text, label: 'Company Description (optional)' %>
    <%= f.button :submit, "continue to step 2", id: "post-job-submit" %>
  </div>
<% end %>

app/views/companies/index.html.erb
<div class="screen">
  <div class="container">
    <div class="list-container">
      <ul>
        <h2>Companies</h2>
        <div class="row">
        <% @companies.each do |company| %>
          <%= link_to company_path(company) do %>
          <div class="col-X">
            <% if company.photo.attached? %>
              <%= cl_image_tag company.photo.key, height: 150, width: 200, crop: :fill %>
              <h3><%= company.name %></h3>
              <% else %>
              <div class="no-logo"></div>
              <h3><%= company.name %></h3>
            <% end %>
          </div>
          <% end %>
        <% end %>
        </div>
      </ul>
    </div>
  </div>
</div>

app/views/companies/new.html.erb
<div class="main-background">
  <div class="header">
    <div class="header-container">
      <h2>Reach the agile Community</h2>
      <ul class='progress'>
        <li>Step 1</li>
        <li>Step 2</li>
        <li>Step 3</li>
      </ul>
      <div class="progress-bar">
        <div id="progress-bar-1"></div>
        <div id="progress-bar-2 hidden"></div>
        <div id="progress-bar-3 hidden"></div>
      </div>
      <ul class="progress posting-steps">
        <li>Post a job</li>
        <li>Preview your ad</li>
        <li>Purchase</li>
      </ul>
    </div>
  </div>
  <div class="container content">
    <%= render 'form' %>
  </div>
</div>

app/views/companies/preview.html.erb
<div class="main-background">
  <div class="header">
    <div class="header-container">
      <h2>Reach the agile Community</h2>
      <ul class='progress'>
        <li>Step 1</li>
        <li>Step 2</li>
        <!-- <li>Step 3</li> -->
      </ul>
      <div class="progress-bar">
        <div id="progress-bar-1 hidden"></div>
        <div id="progress-bar-2"></div>
        <!-- <div id="progress-bar-3 hidden"></div> -->
      </div>
      <ul class="progress posting-steps">
        <li>Post a job</li>
        <li>Preview your ad</li>
        <!-- <li>Purchase</li> -->
      </ul>
    </div>
  </div>
  <div class="container content-container">
    <%= render 'jobs/job-card' %>
  </div>
</div>

app/views/companies/show.html.erb
<div class="clear-background">
  <div class="container content-container">
    <div class="nav">
     <%= link_to "← Back to all jobs", root_path %>
    </div>
    <%#= render 'company-posting' %>

    <div class="company-show">

      <!-- Data card of the company -->
      <div class="company-data">
        <p><%= @company.headquarters  %></p>
        <a href=<% @company.url %>>View website</a>

      </div>

      <div class="company-details">
        <div class="company-details-head">
          <div>
            <h1><%= @company.name %></h1>
            <p>Jobs Posted:<%= @company.jobs.length %></p>
          </div>

          <div class="company-socials">

          </div>
        </div>


      </div>

    </div>
  </div>
</div>

app/views/jobs/_job-card.erb
<div class="content">
  <div class="listing-header">
    <p><%= @job.created_at.strftime('Posted %b %d')  %></p>
    <h1><%= @job.title  %></h1>
    <span class="listing-tag"><%= @job.category %></span>
    <span class="listing-tag"></span>
    <span class="listing-tag"></span>
  </div>
  <div class="company-card">
    <div class="company-logo">
      <%#= image %>
    </div>
    <div class="listing-container">
      <h2><%= @job.company.name %></h2>
    </div>
    <p><%= @job.company.headquarters  %></p>
    <a href="#">View website</a>
    <p>Jobs Posted:<%= @job.company.jobs.length %></p>
    <div class="apply-btn">
      <a href="#" id="post-job-submit">Apply for this position</a>
    </div>
  </div>
  <div class="job" id="job-show">
    <div class= "job-text">
      <div class= ""></div>
      <%= @job.description  %>
    </div>
    <div class="listing-tools">
      <a href="#">View all positions at <%= @job.company.name %></a>
      <%#= link_to "View all positions at #{@job.company}", company_jobs_path(@company) %>
      <div class="apply-btn">
        <a href="#" id="post-job-submit">Apply for this position</a>
      </div>
    </div>
  </div>
</div>

app/views/jobs/_job-posting.erb
<div class="content">

  <!-- header -->
  <div class="listing-header">
    <p><%= @job.created_at.strftime('Posted %b %d')  %></p>
    <h1><%= @job.title  %></h1>
    <h2><%= @job.company.name %></h2>
    <span class="listing-tag"><%= @job.category %></span>
    <span class="listing-tag"><%= @job.job_type %></span>
    <!-- <span class="listing-tag"></span> -->
  </div>

  <!-- listing -->
  <div class="company-card">
    <div class="company-logo">
        <% if @company.photo.attached? %>
          <%= cl_image_tag @company.photo.key, height: 150, width: 200, crop: :fill %>
        <% end %>
    </div>
    <div class="listing-container">
      <%= link_to "<h1>#{ @job.company.name }</h1>".html_safe, company_path(@company), {class: 'h2'}  %>
    </div>
    <p><%= @job.company.headquarters  %></p>
    <a href=<% @job.company.url %>>View website</a>
    <p>Jobs Posted:<%= @job.company.jobs.length %></p>
    <div class="apply-btn">
      <a href="#" id="post-job-submit">Apply for this position</a>
    </div>
    <%= link_to "View all jobs ", company_jobs_path(@company) %>
  </div>
  <section class="job" id="job-show">
    <div class= "job-listing">
      <div class= "job-listing-show">
        <pre><%= @job.description.with_all_richt_text_content  %></pre>
      </div>
    </div>
    <div class="listing-tools">
      <%= link_to "View all positions at #{@job.company.name}", company_jobs_path(@company) %>
      <div class="apply-btn">
        <a href="#" id="post-job-submit">Apply for this position</a>
      </div>
    </div>
  </section>
</div>

app/views/jobs/_preview.html.erb
<div class="content">
  <div class="listing-header">
    <p><%= @job.created_at.strftime('Posted %b %d')  %></p>
    <h1><%= @job.title  %></h1>
    <span class="listing-tag"><%= @job.category %></span>
    <span class="listing-tag"></span>
    <span class="listing-tag"></span>
  </div>
  <div class="company-card">
    <div class="company-logo">
      <%#= image %>
    </div>
    <div class="listing-container">
      <div><%= @job.company.name %></div>
    </div>
  </div>
  <div class="job" id="job-show">
    <div>
      <%= @job.description  %>
    </div>
    <div class="listing-tools">
      <a href="#">View all positions at <%= @job.company.name %></a>
      <%#= link_to "View all positions at #{@job.company}", company_jobs_path(@company) %>
      <div>
        <a href="#" id="post-job-submit">Apply for this position</a>
      </div>
    </div>
  </div>
</div>

app/views/jobs/categories.html.erb
<div class="screen">
  <div class="container">
    <div class="list-container">
      <ul>
        <h2>Agile <%= @job.category %> Jobs</h2>
        <% if @job.category == @job %>
          <% @jobs.each do |job| %>
            <%= link_to job_path(job) do %>
                <% if job.company.photo.attached? %>
                <%= image_tag job.company.logo, width: 40, height: 40, class: "avatar-small" %>
                <% end %>
                  <%if job.new? %>
                  <div class="job-card job-card-new">
                    <p class="new-tag">NEW</p>
                    <div class="job-card-info-infos">
                      <div>
                        <p><%= job.company.name %></p>
                        <h3><%= job.title %></h3>
                      </div>
                    </div>
                    <% if job.featured? %>
                    <p class="featured">Featured</p>
                    <% end %>
                  <% else %>
                  <div class="job-card">
                    <div class="job-card-info-infos">
                      <p><%= job.company.name %></p>
                      <h3><%= job.title %></h3>
                      <p><%= job.created_at.strftime('Posted %b %d') %></p>
                    </div>
                  </div>
                  <% end %>
                </div>
              </a>
            <% end %>
          <% end %>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<header id="header">
  <div class="primary-feature">
    <h1>workagile.io - find your agile job</h1>
  </div>
   <div class="secondary-feature">
    <h2>workagile is a work community for agile jobs in the world. workagile will be the number one destination to find and list incredible agile opportunities.</h2>
  </div>
  <div class="post-job">
    <%= link_to 'Post a job for 249 €', new_path, class: "post-job-btn" %>
  </div>
</header>
<div class="screen">
  <div class="container">
    <div class="list-container">
      <ul>
        <h2>Agile Jobs</h2>
        <% @jobs.each do |job| %>
            <%= link_to job_path(job) do %>
                <% if job.company.photo.attached? %>
                <%= image_tag job.company.logo, width: 40, height: 40, class: "avatar-small" %>
                <% end %>
                  <%if job.new? %>
                  <div class="job-card job-card-new">
                    <p class="new-tag">NEW</p>
                    <div class="job-card-info-infos">
                      <div>
                        <p><%= job.company.name %></p>
                        <h3><%= job.title %></h3>
                      </div>
                    </div>
                    <% if job.featured? %>
                    <p class="featured">Featured</p>
                    <% end %>
                  <% else %>
                  <div class="job-card">
                    <div class="job-card-info-infos">
                      <p><%= job.company.name %></p>
                      <h3><%= job.title %></h3>
                      <p><%= job.created_at.strftime('Posted %b %d') %></p>
                    </div>
                  </div>
                  <% end %>
                </div>
              </a>
            <% end %>
          <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/jobs/new.html.erb
<!-- <div class="main-background">
  <div class="header">
    <div class="header-container">
      <h2>Reach the agile Community</h2>
      <ul class='progress'>
        <li>Step 1</li>
        <li>Step 2</li> -->
        <!-- <li>Step 3</li> -->
     <!--  </ul>
      <div class="progress-bar">
        <div id="progress-bar-1"></div>
        <div id="progress-bar-2 hidden"></div>
        <div id="progress-bar-3 hidden"></div>
      </div>
      <ul class="progress posting-steps">
        <li>Post a job</li>
        <li>Your Company</li>
        <li>Preview</li>
      </ul>
    </div>
  </div>
  <div class="container content"> -->
    <%#= render 'form' %>
 <!--  </div>
</div> -->

app/views/jobs/preview.html.erb
<div class="main-background">
  <div class="header">
    <div class="header-container">
      <h2>Reach the agile Community</h2>
      <ul class='progress'>
        <li>Step 1</li>
        <li>Step 2</li>
        <li>Step 3</li>
      </ul>
      <div class="progress-bar">
        <div id="progress-bar-1 hidden"></div>
        <div id="progress-bar-2"></div>
        <div id="progress-bar-3 hidden"></div>
      </div>
      <ul class="progress posting-steps">
        <li>Post a job</li>
        <li>Preview your ad</li>
        <li>Purchase</li>
      </ul>
    </div>
    <div class="nav">
    <div>
      <%= link_to '<< correct', new_path %>
    </div>
  </div>
  </div>
  <div class="container content-container">
    <%= render 'job-posting' %>
  </div>
  <%= link_to 'Ready', purchase_job_path(@job) %>
</div>

app/views/jobs/purchase.erb
<div class="main-background">
  <div class="header">
    <div class="header-container">
      <h2>Reach the agile Community</h2>
      <ul class='progress'>
        <li>Step 1</li>
        <li>Step 2</li>
        <li>Step 3</li>
      </ul>
      <div class="progress-bar">
        <div id="progress-bar-1 hidden"></div>
        <div id="progress-bar-2 hidden"></div>
        <div id="progress-bar-3"></div>
      </div>
      <ul class="progress posting-steps">
        <li>Post a job</li>
        <li>Preview your ad</li>
        <li>Purchase</li>
      </ul>
    </div>
  </div>
  <div class="container content-container">
    <div class="content message">
      <h3>Thanks you for posting*. </h3>
      <p>
        You have reached the growing agile community on the web.
      </p>
      <p>
        *Will be posted in the next hours
      </p>
    </div>
  </div>
  <div class="container content-container">
    <%= render 'job-posting' %>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="clear-background">
  <div class="container content-container">
    <div class="nav">
     <%= link_to "← Back to all jobs", root_path %>
    </div>
    <%= render 'job-posting' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work Agile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>

    <%= yield %>

    <%= render 'shared/footer' %>
  </body>
</html>

app/views/pages/imprint.html.erb
<div class="main-background">
  <div class="container content-container">
    <div class="content">
      <h1>Impressum</h1>

      <p>Angaben gemäß § 5 TMG:</p>

      <h2>Goldfuchs Ventures UG (haftungsbeschränkt) i.G.</h2>
      <pre>
        Sonnenallee 200
        12059 Berlin
        Kontakt:
        Telefon:+49 30 57711551
        E-Mail: workagile-project@goldfuchs.vc
      </pre>
      <pre>
        Umsatzsteuer-ID:

        Umsatzsteuer-Identifikationsnummer gemäß §27 a Umsatzsteuergesetz:
        angefragt

        **Haftungsausschluss (Disclaimer)
      </pre>
      <p>
        *HAFTUNG FÜR INHALTE
        Als Diensteanbieter sind wir gemäß § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.
        *HAFTUNG FÜR LINKS
        Unser Angebot enthält Links zu externen Webseiten Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.
      </p>
      <p>
        *URHEBERRECHT
        Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.
      </p>
    </div>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">Copyright © 2022</div>
  <div class="footer-links">
    <div>
      <%= link_to 'Imprint', imprint_path %>
    </div>
    <div class="footer-social">
      <!-- <a href=""><i class="fab fa-twitter"></i></a> -->
      <a href="https://www.linkedin.com/in/christian-fuchs-emailmarketing/" target="_blank"><i class="fab fa-linkedin"></i></a>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm">
  <div>
    <%= link_to "/", class: "navbar-brand" do %>
      <h3>Work Agile</h2>
    <% end %>
  </div>
  <div class="section">
    <nav class="flex-container">
      <ul class="navbar-list">
        <li>
          <div class="dropdown show">
            <a href="#"class="navbar-btn flex-item dropdown-toggle" role="button" data-toggle="dropdown">Categories</a>
            <span class="arrow"></span>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
              <a href="#" class="dopdown-item">category #1</a>
              <a href="#" class="dopdown-item">category #2</a>
              <a href="#" class="dopdown-item">category #3</a>
            </div>
          </div>
        </li>
        <li><%= link_to 'Companies', companies_path,class: "navbar-btn flex-item" %></li>
        <li><%= link_to 'post a job', new_company_path, class: "navbar-btn", id: "red-btn" %></li>
      </ul>
  </div>
</div>